import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="136" cy="112" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><path d="M88,168a60,60,0,0,1,96,0" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><rect x="40" y="48" width="192" height="160" rx="8" transform="translate(264 -8) rotate(90)" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  light: <><circle cx="136" cy="112" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><path d="M88,168a60,60,0,0,1,96,0" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><rect x="40" y="48" width="192" height="160" rx="8" transform="translate(264 -8) rotate(90)" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  regular: <><circle cx="136" cy="112" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><path d="M88,168a60,60,0,0,1,96,0" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><rect x="40" y="48" width="192" height="160" rx="8" transform="translate(264 -8) rotate(90)" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  bold: <><circle cx="136" cy="112" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><rect x="40" y="48" width="192" height="160" rx="8" transform="translate(264 -8) rotate(90)" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><path d="M92,163.21a60,60,0,0,1,88,0" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="136" cy="112" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><path d="M88,168a60,60,0,0,1,96,0" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><rect x="40" y="48" width="192" height="160" rx="8" transform="translate(264 -8) rotate(90)" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
};

export const AddressBookIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
