import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><rect x="24" y="56" width="208" height="144" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><polyline points="64 200 88 168 168 168 192 200" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="176" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="80" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  light: <><rect x="24" y="56" width="208" height="144" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><polyline points="64 200 88 168 168 168 192 200" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="176" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="80" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  regular: <><rect x="24" y="56" width="208" height="144" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><polyline points="64 200 88 168 168 168 192 200" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="176" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="80" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  bold: <><rect x="24" y="56" width="208" height="144" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="174" cy="118" r="22" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="82" cy="118" r="22" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/></>,
  fill: <></>,
  duotone: <><rect x="24" y="56" width="208" height="144" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><polyline points="64 200 88 168 168 168 192 200" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="176" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="80" cy="112" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
};

export const CassetteTapeIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
