import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><rect x="104" y="104" width="48" height="48" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="48" y="48" width="160" height="160" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  light: <><rect x="104" y="104" width="48" height="48" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="48" y="48" width="160" height="160" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  regular: <><rect x="104" y="104" width="48" height="48" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="48" y="48" width="160" height="160" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  bold: <><rect x="100" y="100" width="56" height="56" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="48" y="48" width="160" height="160" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  fill: <></>,
  duotone: <><rect x="104" y="104" width="48" height="48" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="48" y="48" width="160" height="160" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
};

export const CpuIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
