import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  light: <><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  regular: <><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  bold: <><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  fill: <><path d="M248,64H8A8,8,0,0,0,8,80h8V192a8,8,0,0,0,16,0V144H224v48a8,8,0,0,0,16,0V80h8a8,8,0,0,0,0-16ZM80,112H56a8,8,0,0,1,0-16H80a8,8,0,0,1,0,16Zm56,8a8,8,0,0,1-16,0V88a8,8,0,0,1,16,0Zm64-8H176a8,8,0,0,1,0-16h24a8,8,0,0,1,0,16Z" fill="currentColor"/></>,
  duotone: <><rect x="24" y="72" width="208" height="64" opacity="0.2" fill="currentColor"/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
};

export const DeskIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
