import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><circle cx="96" cy="96" r="72" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="160" cy="160" r="72" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  light: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><circle cx="96" cy="96" r="72" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="160" cy="160" r="72" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  regular: <><circle cx="96" cy="96" r="72" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="160" cy="160" r="72" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  bold: <><circle cx="96" cy="96" r="72" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="160" cy="160" r="72" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="96" cy="96" r="72" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="160" cy="160" r="72" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/></>,
};

export const ExcludeIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
