import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  light: <><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  regular: <><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  bold: <><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  fill: <><path d="M136,120v96a8,8,0,0,1-16,0V120a8,8,0,0,1,16,0Zm64,72a8,8,0,0,0-8,8v16a8,8,0,0,0,16,0V200A8,8,0,0,0,200,192Zm24-48H208V40a8,8,0,0,0-16,0V144H176a8,8,0,0,0-8,8v16a8,8,0,0,0,8,8h48a8,8,0,0,0,8-8V152A8,8,0,0,0,224,144ZM56,160a8,8,0,0,0-8,8v48a8,8,0,0,0,16,0V168A8,8,0,0,0,56,160Zm24-48H64V40a8,8,0,0,0-16,0v72H32a8,8,0,0,0-8,8v16a8,8,0,0,0,8,8H80a8,8,0,0,0,8-8V120A8,8,0,0,0,80,112Zm72-48H136V40a8,8,0,0,0-16,0V64H104a8,8,0,0,0-8,8V88a8,8,0,0,0,8,8h48a8,8,0,0,0,8-8V72A8,8,0,0,0,152,64Z" fill="currentColor"/></>,
  duotone: <><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><rect x="56" y="40" width="144" height="176" opacity="0.2" fill="currentColor"/></>,
};

export const FadersIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
