import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="148" cy="44" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="212" cy="124" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="156" cy="212" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="56" cy="184" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="52" cy="84" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"4.2s"}}/></>,
  light: <><circle cx="148" cy="44" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="212" cy="124" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="156" cy="212" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="56" cy="184" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="52" cy="84" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"4.2s"}}/></>,
  regular: <><circle cx="148" cy="44" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="212" cy="124" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="156" cy="212" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="56" cy="184" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="52" cy="84" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"4.2s"}}/></>,
  bold: <><circle cx="148" cy="44" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="212" cy="124" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="156" cy="212" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="56" cy="184" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="52" cy="84" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"4.2s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="148" cy="44" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="212" cy="124" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="156" cy="212" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="56" cy="184" r="20" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="52" cy="84" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"3.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"4.2s"}}/></>,
};

export const FediverseLogoIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
