import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line strokeWidth="8" className="draw-line" style={{animationDelay:"0s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"0.3s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"0.6s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"0.9s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"1.2s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"1.5s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"1.8s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"2.1s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"2.4s"}}/><line strokeWidth="8" className="draw-line" style={{animationDelay:"2.7s"}}/></>,
  light: <><line strokeWidth="12" className="draw-line" style={{animationDelay:"0s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"0.3s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"0.6s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"0.9s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"1.2s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"1.5s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"1.8s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"2.1s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"2.4s"}}/><line strokeWidth="12" className="draw-line" style={{animationDelay:"2.7s"}}/></>,
  regular: <><line strokeWidth="16" className="draw-line" style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"2.4s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"2.7s"}}/></>,
  bold: <><line strokeWidth="24" className="draw-line" style={{animationDelay:"0s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"0.3s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"0.6s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"0.9s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"1.2s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"1.5s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"1.8s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"2.1s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"2.4s"}}/><line strokeWidth="24" className="draw-line" style={{animationDelay:"2.7s"}}/></>,
  fill: <><path d="M80,192a8,8,0,0,1-8,8H32a8,8,0,0,1,0-16H72A8,8,0,0,1,80,192Zm144-8H184a8,8,0,0,0,0,16h40a8,8,0,0,0,0-16Zm-72,0H104a8,8,0,0,0,0,16h48a8,8,0,0,0,0-16ZM32,168h80a8,8,0,0,0,0-16H32a8,8,0,0,0,0,16Zm192-16H144a8,8,0,0,0,0,16h80a8,8,0,0,0,0-16Zm0-96H32a8,8,0,0,0-8,8V88a8,8,0,0,0,8,8H224a8,8,0,0,0,8-8V64A8,8,0,0,0,224,56Zm0,56H32a8,8,0,0,0-8,8v8a8,8,0,0,0,8,8H224a8,8,0,0,0,8-8v-8A8,8,0,0,0,224,112Z" fill="currentColor"/></>,
  duotone: <><rect x="32" y="64" width="192" height="120" opacity="0.2" fill="currentColor"/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"2.4s"}}/><line strokeWidth="16" className="draw-line" style={{animationDelay:"2.7s"}}/></>,
};

export const GradientIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
