import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="128" cy="128" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="96" cy="56" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="104" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="200" cy="184" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="56" cy="192" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  light: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="128" cy="128" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><circle cx="96" cy="56" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><circle cx="200" cy="104" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="200" cy="184" r="24" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><circle cx="56" cy="192" r="24" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  regular: <><circle cx="128" cy="128" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="96" cy="56" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="104" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="200" cy="184" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="56" cy="192" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  bold: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="128" cy="128" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><circle cx="96" cy="56" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><circle cx="200" cy="100" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="200" cy="188" r="24" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><circle cx="56" cy="192" r="24" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  fill: <></>,
  duotone: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><circle cx="128" cy="128" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><circle cx="96" cy="56" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><circle cx="200" cy="104" r="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="200" cy="184" r="24" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><circle cx="56" cy="192" r="24" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
};

export const GraphIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
