import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="96" cy="160" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><path d="M141.25,205.25a64,64,0,1,1-90.5-90.5L133.49,32" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  light: <><circle cx="96" cy="160" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><path d="M141.25,205.25a64,64,0,1,1-90.5-90.5L133.49,32" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  regular: <><circle cx="96" cy="160" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><path d="M141.25,205.25a64,64,0,1,1-90.5-90.5L133.49,32" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  bold: <><circle cx="96" cy="160" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><path d="M141.25,205.25a64,64,0,1,1-90.5-90.5L133.49,32" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="96" cy="160" r="32" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><path d="M141.25,205.25a64,64,0,1,1-90.5-90.5L133.49,32" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
};

export const MeteorIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
