import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="180" cy="164" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="52" cy="196" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><polyline points="80 196 80 56 136 42" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  light: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="180" cy="164" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="52" cy="196" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><polyline points="80 196 80 56 136 42" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  regular: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="180" cy="164" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="52" cy="196" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><polyline points="80 196 80 56 136 42" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  bold: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="180" cy="164" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="52" cy="196" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><polyline points="80 196 80 56 136 42" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <></>,
  duotone: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="180" cy="164" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="52" cy="196" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><polyline points="80 196 80 56 136 42" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
};

export const MusicNotesMinusIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
