import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><rect x="104" y="32" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="40" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><rect x="168" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  light: <><rect x="104" y="32" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="40" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><rect x="168" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  regular: <><rect x="104" y="32" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="40" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><rect x="168" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  bold: <><rect x="104" y="32" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="40" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><rect x="168" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  fill: <></>,
  duotone: <><rect x="104" y="32" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="40" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><rect x="168" y="168" width="48" height="48" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
};

export const NetworkIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
