import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/></>,
  light: <><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/></>,
  regular: <><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/></>,
  bold: <><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/></>,
  fill: <><path d="M224,48H32A16,16,0,0,0,16,64V192a16,16,0,0,0,16,16H224a16,16,0,0,0,16-16V64A16,16,0,0,0,224,48Zm-19.42,94.71a8,8,0,1,1-13,9.41L184,141.61l-7.63,10.51a8,8,0,1,1-13-9.41l7.64-10.5-12.36-4a8,8,0,1,1,5-15.21L176,117V104a8,8,0,0,1,16,0v13l12.35-4a8,8,0,0,1,5,15.21l-12.36,4Zm-72,0a8,8,0,1,1-13,9.41L112,141.61l-7.63,10.51a8,8,0,1,1-13-9.41l7.64-10.5-12.36-4a8,8,0,1,1,5-15.21L104,117V104a8,8,0,0,1,16,0v13l12.35-4a8,8,0,1,1,5,15.21l-12.36,4ZM64,88v80a8,8,0,0,1-16,0V88a8,8,0,0,1,16,0Z" fill="currentColor"/></>,
  duotone: <><path d="M240,56H16A16,16,0,0,0,0,72V184a16,16,0,0,0,16,16H240a16,16,0,0,0,16-16V72A16,16,0,0,0,240,56Z" opacity="0.2" fill="currentColor"/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"3s"}}/></>,
};

export const PasswordIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
