import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="128" cy="128" r="96" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="128" r="56" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  light: <><circle cx="128" cy="128" r="96" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="128" r="56" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  regular: <><circle cx="128" cy="128" r="96" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="128" r="56" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  bold: <><circle cx="128" cy="128" r="96" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="128" r="48" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="128" cy="128" r="96" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="128" r="56" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
};

export const PokerChipIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
