import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="120" cy="48" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="40" cy="120" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="160" cy="208" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="208" cy="72" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  light: <><circle cx="120" cy="48" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="40" cy="120" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="160" cy="208" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="208" cy="72" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  regular: <><circle cx="120" cy="48" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="40" cy="120" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="160" cy="208" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="208" cy="72" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  bold: <><circle cx="120" cy="48" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="40" cy="120" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="160" cy="208" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="208" cy="72" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="120" cy="48" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="40" cy="120" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="160" cy="208" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><circle cx="208" cy="72" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
};

export const PolygonIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
