import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  light: <><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  regular: <><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  bold: <><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <><path d="M79.25,38.69a4,4,0,0,1,3-6.69H192a8,8,0,0,1,8,8.53A8.17,8.17,0,0,1,191.73,48h-6.19L206.7,167.91a4,4,0,0,1-6.9,3.39ZM213.92,210.62l-160-176A8,8,0,1,0,42.08,45.38L66.24,72,49.29,168H40a8,8,0,0,0,0,16h80v56a8,8,0,0,0,16,0V184h32.1l34,37.38a8,8,0,1,0,11.84-10.76Z" fill="currentColor"/></>,
  duotone: <><path d="M56,176,78.83,46.61A8,8,0,0,1,86.71,40H176l22.34,126.61a8,8,0,0,1-7.88,9.39Z" opacity="0.2" fill="currentColor"/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
};

export const PushPinSimpleSlashIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
