import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><rect x="56" y="48" width="144" height="160" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><polygon points="128 88 104 128 128 168 152 128 128 88" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  light: <><rect x="56" y="48" width="144" height="160" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><polygon points="128 88 104 128 128 168 152 128 128 88" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  regular: <><rect x="56" y="48" width="144" height="160" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><polygon points="128 88 104 128 128 168 152 128 128 88" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  bold: <><rect x="56" y="48" width="144" height="160" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><polygon points="128 88 104 128 128 168 152 128 128 88" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  fill: <></>,
  duotone: <><rect x="56" y="48" width="144" height="160" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><polygon points="128 88 104 128 128 168 152 128 128 88" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
};

export const RugIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
