import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="56" cy="136" r="24" strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="168" r="24" strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="8" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  light: <><circle cx="56" cy="136" r="24" strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="168" r="24" strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="12" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  regular: <><circle cx="56" cy="136" r="24" strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="168" r="24" strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  bold: <><circle cx="56" cy="136" r="24" strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="168" r="24" strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="24" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  fill: <><path d="M84,136a28,28,0,0,1-20,26.83V216a8,8,0,0,1-16,0V162.83a28,28,0,0,1,0-53.66V40a8,8,0,0,1,16,0v69.17A28,28,0,0,1,84,136Zm52-74.83V40a8,8,0,0,0-16,0V61.17a28,28,0,0,0,0,53.66V216a8,8,0,0,0,16,0V114.83a28,28,0,0,0,0-53.66Zm72,80V40a8,8,0,0,0-16,0V141.17a28,28,0,0,0,0,53.66V216a8,8,0,0,0,16,0V194.83a28,28,0,0,0,0-53.66Z" fill="currentColor"/></>,
  duotone: <><circle cx="56" cy="136" r="24" opacity="0.2" fill="currentColor"/><circle cx="128" cy="88" r="24" opacity="0.2" fill="currentColor"/><circle cx="200" cy="168" r="24" opacity="0.2" fill="currentColor"/><circle cx="56" cy="136" r="24" strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="200" cy="168" r="24" strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line strokeWidth="16" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
};

export const SlidersIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
