import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><polyline points="96 56 128 24 160 56" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="160 200 128 232 96 200" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  light: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><polyline points="96 56 128 24 160 56" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="160 200 128 232 96 200" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  regular: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><polyline points="96 56 128 24 160 56" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="160 200 128 232 96 200" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  bold: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><polyline points="96 56 128 24 160 56" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="160 200 128 232 96 200" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <></>,
  duotone: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><polygon points="96 56 128 24 160 56 96 56" className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polygon points="160 200 128 232 96 200 160 200" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
};

export const SplitVerticalIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
