import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="76" cy="188" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="144 80 144 40 184 40" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><path d="M144,40l16,16c40,40,8,88-24,96" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  light: <><circle cx="76" cy="188" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="144 80 144 40 184 40" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><path d="M144,40l16,16c40,40,8,88-24,96" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  regular: <><circle cx="76" cy="188" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="144 80 144 40 184 40" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><path d="M144,40l16,16c40,40,8,88-24,96" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  bold: <><circle cx="80" cy="184" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="148 84 148 44 188 44" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><path d="M148,44l12,12c38.33,38.33,10.55,84-20,94.79" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="76" cy="188" r="28" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><polyline points="144 80 144 40 184 40" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><path d="M144,40l16,16c40,40,8,88-24,96" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
};

export const StrategyIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
