import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><path d="M40,208V96a64,64,0,0,1,64-64h48a64,64,0,0,1,64,64V208" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="80" y="80" width="96" height="104" rx="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  light: <><path d="M40,208V96a64,64,0,0,1,64-64h48a64,64,0,0,1,64,64V208" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="80" y="80" width="96" height="104" rx="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  regular: <><path d="M40,208V96a64,64,0,0,1,64-64h48a64,64,0,0,1,64,64V208" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="80" y="80" width="96" height="104" rx="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  bold: <><path d="M40,208V96a64,64,0,0,1,64-64h48a64,64,0,0,1,64,64V208" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="80" y="80" width="96" height="104" rx="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/></>,
  fill: <></>,
  duotone: <><path d="M40,208V96a64,64,0,0,1,64-64h48a64,64,0,0,1,64,64V208" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><rect x="80" y="80" width="96" height="104" rx="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
};

export const SubwayIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
