import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><rect x="64" y="32" width="128" height="192" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="128" cy="168" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  light: <><rect x="64" y="32" width="128" height="192" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="128" cy="168" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  regular: <><rect x="64" y="32" width="128" height="192" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="128" cy="168" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  bold: <><rect x="64" y="32" width="128" height="192" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><circle cx="128" cy="88" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><circle cx="128" cy="168" r="20" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  fill: <></>,
  duotone: <><rect x="64" y="32" width="128" height="192" rx="8" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="128" cy="88" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="128" cy="168" r="24" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
};

export const TrafficSignalIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
