import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="200" cy="56" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="128" cy="120" r="40" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><path d="M63.8,199.37a72,72,0,0,1,128.4,0" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><path d="M222.67,112A95.92,95.92,0,1,1,144,33.33" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  light: <><circle cx="200" cy="56" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="128" cy="120" r="40" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><path d="M63.8,199.37a72,72,0,0,1,128.4,0" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><path d="M222.67,112A95.92,95.92,0,1,1,144,33.33" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  regular: <><circle cx="200" cy="56" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="128" cy="120" r="40" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><path d="M63.8,199.37a72,72,0,0,1,128.4,0" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><path d="M222.67,112A95.92,95.92,0,1,1,144,33.33" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
  bold: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><circle cx="128" cy="120" r="40" className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><path d="M63.8,199.37a72,72,0,0,1,128.4,0" className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><path d="M222.67,112A95.92,95.92,0,1,1,144,33.33" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/></>,
  fill: <></>,
  duotone: <><line className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><circle cx="200" cy="56" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><circle cx="128" cy="120" r="40" className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><path d="M63.8,199.37a72,72,0,0,1,128.4,0" className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/><path d="M222.67,112A95.92,95.92,0,1,1,144,33.33" className="draw-line" pathLength={1} style={{animationDelay:"2.7s"}}/></>,
};

export const UserCircleGearIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
