import '../styles.css';
import { Icon, type IconWeights } from '../Icon';
import type { IconProps } from '../types';

const WEIGHTS: IconWeights = {
  thin: <><circle cx="108" cy="100" r="60" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><path d="M24,200c20.55-24.45,49.56-40,84-40s63.45,15.55,84,40" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="224" cy="136" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  light: <><circle cx="108" cy="100" r="60" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><path d="M24,200c20.55-24.45,49.56-40,84-40s63.45,15.55,84,40" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="224" cy="136" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  regular: <><circle cx="108" cy="100" r="60" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><path d="M24,200c20.55-24.45,49.56-40,84-40s63.45,15.55,84,40" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="224" cy="136" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
  bold: <><circle cx="104" cy="100" r="60" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><path d="M20,200c20.55-24.45,49.56-40,84-40s63.45,15.55,84,40" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/></>,
  fill: <></>,
  duotone: <><circle cx="108" cy="100" r="60" className="draw-line" pathLength={1} style={{animationDelay:"0s"}}/><path d="M24,200c20.55-24.45,49.56-40,84-40s63.45,15.55,84,40" className="draw-line" pathLength={1} style={{animationDelay:"0.3s"}}/><circle cx="224" cy="136" r="16" className="draw-line" pathLength={1} style={{animationDelay:"0.6s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"0.9s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.2s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.5s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"1.8s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.1s"}}/><line className="draw-line" pathLength={1} style={{animationDelay:"2.4s"}}/></>,
};

export const UserGearIcon = (props: IconProps) => <Icon weights={WEIGHTS} {...props} />;
